version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    # Critical linters - must pass
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis (includes gosimple)
    - unused        # Find unused code
    - gosec         # Security checker

    # Important linters
    - bodyclose     # Check HTTP response body is closed
    - rowserrcheck  # Check sql.Rows.Err is checked
    - sqlclosecheck # Check sql.Rows/sql.Stmt are closed
    - misspell      # Find misspelled words

    # Code quality linters
    - copyloopvar   # Find places where loop variables are copied
    - unconvert     # Remove unnecessary type conversions

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false  # Don't check blank assignments (_)
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.Rows).Close
        - (*database/sql.DB).Close

    gosec:
      excludes:
        - G404 # Use of weak random number generator - we use crypto/rand where needed
        - G204 # Subprocess with variable - acceptable in some cases

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - _test\.go$

issues:
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
