version: '3'

services:
  deadmanswitch:
    ports:
      - "8082:8080"
    environment:
      - BASE_DOMAIN=localhost:8082
      - DEBUG=true
      # For testing, we'll use a simple configuration without email verification
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_FROM=test@example.com
