version: '3'

services:
  deadmanswitch:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ${DATA_DIR:-./data}:/app/data
    environment:
      # Required environment variables
      - BASE_DOMAIN=${BASE_DOMAIN:-localhost}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN:-}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}

      # Database settings
      - DBPath=${DB_PATH:-/app/data/deadmanswitch.db}

      # SMTP settings
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - SMTP_FROM=${SMTP_FROM:-}

      # Ping settings
      - PING_FREQUENCY=${PING_FREQUENCY:-1}
      - PING_DEADLINE=${PING_DEADLINE:-7}

      # Debug settings
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    restart: unless-stopped