name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Optionally enable manual workflow trigger
  workflow_dispatch:

jobs:
  test:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out -covermode=atomic ./...
          go tool cover -func=coverage.out

      - name: Generate coverage report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html
          retention-days: 7

      - name: Calculate dynamic coverage threshold
        run: |
          # Get the number of commits
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "Total commits: $COMMIT_COUNT"

          # Calculate the dynamic threshold: 20% + 0.1% per commit, capped at 80%
          THRESHOLD=$(echo "20 + 0.1 * $COMMIT_COUNT" | bc)
          if (( $(echo "$THRESHOLD > 80" | bc -l) )); then
            THRESHOLD=80
          fi
          echo "Dynamic coverage threshold: $THRESHOLD%"
          echo "THRESHOLD=$THRESHOLD" >> $GITHUB_ENV

          # Get the current coverage
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "Total coverage: $COVERAGE%"
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

          # Check if coverage is below the threshold
          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
            echo "Code coverage is below the dynamic threshold of $THRESHOLD%"
            exit 1
          fi